{
 "title": "Consumo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Continuo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consumo Grid",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\ntimeStart = uint(v: v.timeRangeStart)\r\ntimeStop = uint(v: v.timeRangeStop)\r\nrangeSeconds = int(v: duration(v: timeStop - timeStart))\r\naggregation = duration(v: rangeSeconds / 6000)\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"meter_p\")\r\n  |> aggregateWindow(every: aggregation, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: math.mMax(x: 0.0, y: float(v:r._value) * -1.0)}))\r\n"
    }
   ]
  },
  {
   "title": "Consumo Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\ntimeStart = uint(v: v.timeRangeStart)\r\ntimeStop = uint(v: v.timeRangeStop)\r\nrangeSeconds = int(v: duration(v: timeStop - timeStart))\r\naggregation = duration(v: rangeSeconds / 6000)\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: aggregation, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: ( (r.inverter_ac_p * 1000.0) - (math.mMax(x: 0.0, y: float(v:r.meter_p))) + (math.mMax(x: 0.0, y: float(v:r.meter_p) * -1.0)) ) }))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Potencia Exportada",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\ntimeStart = uint(v: v.timeRangeStart)\r\ntimeStop = uint(v: v.timeRangeStop)\r\nrangeSeconds = int(v: duration(v: timeStop - timeStart))\r\naggregation = duration(v: rangeSeconds / 6000)\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"meter_p\")\r\n  |> aggregateWindow(every: aggregation, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: math.mMax(x: 0.0, y: float(v:r._value))}))\r\n"
    }
   ]
  },
  {
   "title": "Consumo Solar",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\ntimeStart = uint(v: v.timeRangeStart)\r\ntimeStop = uint(v: v.timeRangeStop)\r\nrangeSeconds = int(v: duration(v: timeStop - timeStart))\r\naggregation = duration(v: rangeSeconds / 6000)\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: aggregation, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: ((r.inverter_ac_p * 1000.0) - (math.mMax(x: 0.0, y: float(v:r.meter_p))))}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n\r\n"
    }
   ]
  },
  {
   "title": "Potencia Generada",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "timeStart = uint(v: v.timeRangeStart)\r\ntimeStop = uint(v: v.timeRangeStop)\r\nrangeSeconds = int(v: duration(v: timeStop - timeStart))\r\naggregation = duration(v: rangeSeconds / 6000)\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"sun2000\" and\r\n    r._field == \"inverter_ac_p\"\r\n  )\r\n  |> aggregateWindow(every: aggregation, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Comparativa Consumo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"influxdata/influxdb/schema\"\r\n\r\ntimeStart = uint(v: v.timeRangeStart)\r\ntimeStop = uint(v: v.timeRangeStop)\r\nrangeSeconds = int(v: duration(v: timeStop - timeStart))\r\naggregation = duration(v: rangeSeconds / 6000)\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: aggregation, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: ((r.inverter_ac_p * 1000.0) - (math.mMax(x: 0.0, y: float(v:r.meter_p))))}))\r\n  |> map(fn: (r) => ({r with _field: \"solar\"}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n  |> schema.fieldsAsCols()\r\n  |> yield(name: \"Consumo solar\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: aggregation, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: ( (r.inverter_ac_p * 1000.0) - (math.mMax(x: 0.0, y: float(v:r.meter_p))) + (math.mMax(x: 0.0, y: float(v:r.meter_p) * -1.0)) ) }))\r\n  |> map(fn: (r) => ({r with _field: \"total\"}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n  |> schema.fieldsAsCols()\r\n  |> yield(name: \"Consumo total\")\r\n\r\n"
    }
   ]
  },
  { "title": "Día", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Comparativa Consumo",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\nimport \"influxdata/influxdb/schema\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1d), stop: date.add(d: 1d, to: date.truncate(t: v.timeRangeStart, unit: 1d)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: r.inverter_ac_p - (math.mMax(x: 0.0, y: float(v: r.meter_p) * 0.001))}))\r\n  |> aggregateWindow(every: 1h,\r\n    fn: (tables=<-, column) =>\r\n      tables\r\n        |> integral(unit: 1h))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1h, from: r._time)}))\r\n  |> map(fn: (r) => ({r with _field: \"solar\"}))\r\n  |> schema.fieldsAsCols()\r\n  |> yield(name: \"solar\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1d), stop: date.add(d: 1d, to: date.truncate(t: v.timeRangeStart, unit: 1d)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: (r.inverter_ac_p) - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001)) + (math.mMax(x: 0.0, y: float(v:r.meter_p) * -0.001))}))\r\n  |> aggregateWindow(every: 1h,\r\n    fn: (tables=<-, column) =>\r\n      tables\r\n        |> integral(unit: 1h))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1h, from: r._time)}))\r\n  |> map(fn: (r) => ({r with _field: \"total\"}))\r\n  |> schema.fieldsAsCols()\r\n  |> yield(name: \"total\")"
    }
   ]
  },
  {
   "title": "Consumo Grid",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1d), stop: date.add(d: 1d, to: date.truncate(t: v.timeRangeStart, unit: 1d)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"meter_p\")\r\n  |> map(fn: (r) => ({r with _value: math.mMax(x: 0.0, y: float(v:r._value) * -0.001)}))\r\n  |> aggregateWindow(\r\n    every: 1h,\r\n    fn: (tables=<-, column) =>\r\n      tables\r\n        |> integral(unit: 1h))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1h, from: r._time)}))\r\n"
    }
   ]
  },
  {
   "title": "Consumo Solar",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1d), stop: date.add(d: 1d, to: date.truncate(t: v.timeRangeStart, unit: 1d)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: r.inverter_ac_p - (math.mMax(x: 0.0, y: float(v: r.meter_p) * 0.001))}))\r\n  |> aggregateWindow(every: 1h,\r\n    fn: (tables=<-, column) =>\r\n      tables\r\n        |> integral(unit: 1h))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1h, from: r._time)}))\r\n"
    }
   ]
  },
  {
   "title": "Consumo Total",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1d), stop: date.add(d: 1d, to: date.truncate(t: v.timeRangeStart, unit: 1d)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: (r.inverter_ac_p) - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001)) + (math.mMax(x: 0.0, y: float(v:r.meter_p) * -0.001))}))\r\n  |> aggregateWindow(every: 1h,\r\n    fn: (tables=<-, column) =>\r\n      tables\r\n        |> integral(unit: 1h))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1h, from: r._time)}))\r\n"
    }
   ]
  },
  {
   "title": "Potencia Generada",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1d), stop: date.add(d: 1d, to: date.truncate(t: v.timeRangeStart, unit: 1d)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\" and r._field == \"inverter_ac_p\")\r\n  |> aggregateWindow(every: 1h,\r\n    fn: (tables=<-, column) =>\r\n      tables\r\n        |> integral(unit: 1h))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1h, from: r._time)}))\r\n\r\n"
    }
   ]
  },
  {
   "title": "Potencia Exportada",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1d), stop: date.add(d: 1d, to: date.truncate(t: v.timeRangeStart, unit: 1d)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"meter_p\")\r\n  |> map(fn: (r) => ({r with _value: math.mMax(x: 0.0, y: float(v:r._value) * 0.001)}))\r\n  |> aggregateWindow(every: 1h,\r\n    fn: (tables=<-, column) =>\r\n      tables\r\n        |> integral(unit: 1h))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1h, from: r._time)}))\r\n"
    }
   ]
  },
  {
   "title": "Semana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Comparativa Consumo",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "targets": [
      {
       "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\nimport \"influxdata/influxdb/schema\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1w), stop: date.add(d: 1w, to: date.truncate(t: v.timeRangeStart, unit: 1w)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: ((r.inverter_ac_p) - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001)))}))\r\n  |> map(fn: (r) => ({r with _field: \"solar\"}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1d, from: r._time)}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n  |> schema.fieldsAsCols()\r\n  |> yield(name: \"Consumo Solar\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1w), stop: date.add(d: 1w, to: date.truncate(t: v.timeRangeStart, unit: 1w)))  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: r.inverter_ac_p - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001)) + (math.mMax(x: 0.0, y: float(v:r.meter_p) * -0.001))}))\r\n  |> map(fn: (r) => ({r with _field: \"total\"}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1d, from: r._time)}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n  |> schema.fieldsAsCols()\r\n  |> yield(name: \"total\")\r\n"
      }
     ]
    },
    {
     "title": "Consumo Grid",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1w), stop: date.add(d: 1w, to: date.truncate(t: v.timeRangeStart, unit: 1w)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"meter_p\")\r\n  |> map(fn: (r) => ({r with _value: math.mMax(x: 0.0, y: float(v:r._value) * -1.0)}))\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1h, from: r._time)}))"
      }
     ]
    },
    {
     "title": "Consumo Solar",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1w), stop: date.add(d: 1w, to: date.truncate(t: v.timeRangeStart, unit: 1w)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: r.inverter_ac_p - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001))}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1h, from: r._time)}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n"
      }
     ]
    },
    {
     "title": "Consumo Total",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1w), stop: date.add(d: 1w, to: date.truncate(t: v.timeRangeStart, unit: 1w)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: (r.inverter_ac_p) - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001)) + (math.mMax(x: 0.0, y: float(v:r.meter_p) * -0.001))}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1h, from: r._time)}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n"
      }
     ]
    },
    {
     "title": "Potencia Generada",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "query": "import \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1w), stop: date.add(d: 1w, to: date.truncate(t: v.timeRangeStart, unit: 1w)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\" and r._field == \"inverter_ac_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1h, from: r._time)}))\r\n"
      }
     ]
    },
    {
     "title": "Potencia Exportada",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1w), stop: date.add(d: 1w, to: date.truncate(t: v.timeRangeStart, unit: 1w)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: math.mMax(x: 0.0, y: float(v:r._value) * 0.001)}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1h, from: r._time)}))\r\n"
      }
     ]
    }
   ]
  },
  { "title": "Mes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Comparativa Consumo",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\nimport \"influxdata/influxdb/schema\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1mo), stop: date.add(d: 1mo, to: date.truncate(t: v.timeRangeStart, unit: 1mo)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: ((r.inverter_ac_p) - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001)))}))\r\n  |> map(fn: (r) => ({r with _field: \"solar\"}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1d, from: r._time)}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n  |> schema.fieldsAsCols()\r\n  |> yield(name: \"Consumo Solar\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1mo), stop: date.add(d: 1mo, to: date.truncate(t: v.timeRangeStart, unit: 1mo)))  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: r.inverter_ac_p - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001)) + (math.mMax(x: 0.0, y: float(v:r.meter_p) * -0.001))}))\r\n  |> map(fn: (r) => ({r with _field: \"total\"}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1d, from: r._time)}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n  |> schema.fieldsAsCols()\r\n  |> yield(name: \"total\")\r\n"
    }
   ]
  },
  {
   "title": "Consumo Grid",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1mo), stop: date.add(d: 1mo, to: date.truncate(t: v.timeRangeStart, unit: 1mo)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"meter_p\")\r\n  |> map(fn: (r) => ({r with _value: math.mMax(x: 0.0, y: float(v:r._value) * -0.001)}))\r\n  |> aggregateWindow(\r\n    every: 1d,\r\n    fn: (tables=<-, column) =>\r\n      tables\r\n        |> integral(unit: 1h))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1d, from: r._time)}))\r\n"
    }
   ]
  },
  {
   "title": "Consumo Solar",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1mo), stop: date.add(d: 1mo, to: date.truncate(t: v.timeRangeStart, unit: 1mo)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: r.inverter_ac_p - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001))}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1d, from: r._time)}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n"
    }
   ]
  },
  {
   "title": "Consumo Total",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1mo), stop: date.add(d: 1mo, to: date.truncate(t: v.timeRangeStart, unit: 1mo)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: (r.inverter_ac_p) - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001)) + (math.mMax(x: 0.0, y: float(v:r.meter_p) * -0.001))}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1d, from: r._time)}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n"
    }
   ]
  },
  {
   "title": "Potencia Generada",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1mo), stop: date.add(d: 1mo, to: date.truncate(t: v.timeRangeStart, unit: 1mo)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\" and r._field == \"inverter_ac_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1d, from: r._time)}))\r\n"
    }
   ]
  },
  {
   "title": "Potencia Exportada",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1mo), stop: date.add(d: 1mo, to: date.truncate(t: v.timeRangeStart, unit: 1mo)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: math.mMax(x: 0.0, y: float(v:r._value) * 0.001)}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1d, from: r._time)}))\r\n"
    }
   ]
  },
  {
   "title": "Año",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "collapsed": true,
   "panels": [
    {
     "title": "Comparativa Consumo",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "targets": [
      {
       "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\nimport \"influxdata/influxdb/schema\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1y), stop: date.add(d: 1y, to: date.truncate(t: v.timeRangeStart, unit: 1y)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: ((r.inverter_ac_p) - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001)))}))\r\n  |> map(fn: (r) => ({r with _field: \"solar\"}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1mo, from: r._time)}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n  |> schema.fieldsAsCols()\r\n  |> yield(name: \"Consumo Solar\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1y), stop: date.add(d: 1y, to: date.truncate(t: v.timeRangeStart, unit: 1y)))  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: r.inverter_ac_p - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001)) + (math.mMax(x: 0.0, y: float(v:r.meter_p) * -0.001))}))\r\n  |> map(fn: (r) => ({r with _field: \"total\"}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1mo, from: r._time)}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n  |> schema.fieldsAsCols()\r\n  |> yield(name: \"total\")\r\n"
      }
     ]
    },
    {
     "title": "Consumo Grid",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1y), stop: date.add(d: 1y, to: date.truncate(t: v.timeRangeStart, unit: 1y)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"meter_p\")\r\n  |> map(fn: (r) => ({r with _value: math.mMax(x: 0.0, y: float(v:r._value) * -1.0)}))\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1mo, from: r._time)}))"
      }
     ]
    },
    {
     "title": "Consumo Solar",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1y), stop: date.add(d: 1y, to: date.truncate(t: v.timeRangeStart, unit: 1y)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: r.inverter_ac_p - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001))}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1mo, from: r._time)}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n"
      }
     ]
    },
    {
     "title": "Consumo Total",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1y), stop: date.add(d: 1y, to: date.truncate(t: v.timeRangeStart, unit: 1y)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"inverter_ac_p\" or r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: (r.inverter_ac_p) - (math.mMax(x: 0.0, y: float(v:r.meter_p) * 0.001)) + (math.mMax(x: 0.0, y: float(v:r.meter_p) * -0.001))}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1mo, from: r._time)}))\r\n  |> drop(columns: [\"inverter_ac_p\", \"meter_p\"])\r\n"
      }
     ]
    },
    {
     "title": "Potencia Generada",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "query": "import \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1y), stop: date.add(d: 1y, to: date.truncate(t: v.timeRangeStart, unit: 1y)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\" and r._field == \"inverter_ac_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1mo, from: r._time)}))\r\n"
      }
     ]
    },
    {
     "title": "Potencia Exportada",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "query": "import \"math\"\r\nimport \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"Europe/Madrid\")\r\n\r\nfrom(bucket: \"sensors\")\r\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1y), stop: date.add(d: 1y, to: date.truncate(t: v.timeRangeStart, unit: 1y)))\r\n  |> filter(fn: (r) => r._measurement == \"sun2000\")\r\n  |> filter(fn: (r) => r._field == \"meter_p\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 1mo, fn: sum, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: math.mMax(x: 0.0, y: float(v:r._value) * 0.001)}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 1mo, from: r._time)}))\r\n"
      }
     ]
    }
   ]
  }
 ]
}